### ISSUE TITLE
Generate addresses from extended pub key

### ISSUE THREAD

**Issue by zebpaypeswani** [cobowallet/tron-wallet#1]
Hi how can I generate addresses from extended pub key

**Comment by LIU9293** [comment]
Hi, currently not support, thanks for interesting in this project.
This feature should be available, we will improve the code structure.
Actually, you can get some clue from the code:
```
getAddress () {
    const addressBytes = computeAddress(getPubKeyFromPriKey(this._priKeyBytes), this._isTestNet)
    return getBase58CheckAddress(addressBytes)
}
```
`computeAddress` only need the pubkey, please make a PR if you can figure out how to do that.

**Comment by LIU9293** [comment]
Closed due to pull request
