### ISSUE TITLE
Broadcast transaction

### ISSUE THREAD

**Issue by sunny112** [cobowallet/tron-wallet#3]
Hi,
I am looking for broadcast function in Tronscan, but I can not find it. Can I ask which api can be used for broadcast signed transaction?

Thank you for taking time to read my issue.

**Comment by LIU9293** [comment]
Hello sunny, to broadcast a raw transaction, just call TRON Node RPC api, it is not a wallet library function.

**Comment by ahamedbathru** [comment]
Hello Team, 
                       I am a Crypto developer and have few queries regarding the withdraw function in Tron. I am trying to withdraw Tron my exchange using the below methods

    1. CreateTransaction, gettransactionsign ,BroadcastTransaction 
    2.easytransferbyprivate 

I tried to withdraw using the above methods, I have got the success results (Raw Data). But the funds are not moved to the external wallet and could not find the transaction in the explorer. So it would be great if help me to get this transaction successful. 


Thanks in advance
