### ISSUE TITLE
TypeError: Expected Buffer when running node.getAddress()

### ISSUE THREAD

**Issue by or2008** [cobowallet/tron-wallet#5]
Hi guys, I am playing with your cool project and trying to create a wallet using this lib, this is the code I am using:

```
const mnemonic = TronWallet.generateMnemonic();
const node = TronWallet.fromMnemonic(mnemonic)
node.getTronPrivateKey()  // works OK!
node.getAddress() // fail
```

when running the last line, there is an exception:

```
 TypeError: Expected Buffer
      at Object.encode (node_modules/base-x/index.js:29:41)
      at getBase58CheckAddress (node_modules/tron-wallet/dist/index.cjs.js:40:26)
      at TronWallet.getAddress (node_modules/tron-wallet/dist/index.cjs.js:240:12)
      at createWalletByMnemonic (src/plugins/tron.ts:7:22)
```

**Comment by or2008** [comment]
btw, I am using this version 0.1.3 from
https://www.npmjs.com/package/tron-wallet

**Comment by huazhouwang** [comment]
Hi @or2008: 
please make sure your version of `base-x` is 3.0.4 or below in your lock file. We recommend using yarn so that it stays consistent with our dependencies.

**Comment by or2008** [comment]
I see, Thank you!
